#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import difflib
import hashlib
import os
from pathlib import Path
import textwrap
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
BOOTSTRAP = ROOT / "bootstrap"
FIXTURES = ROOT / "tests" / "migration"
VERSION = "MADP-v0.3.0-alpha.1"
SOURCE_BRANCH = "feature/v0.3.0-alpha.1"
SELF_CONTAINED_SOURCES = [
    "protocol/MADP-v0.3.0-alpha.1.md",
    "protocol/GLOSSARY-v0.3.0-alpha.1.md",
    "schemas/generated/session-state-v0.3.0-alpha.1.bundle.schema.yaml",
    "schemas/generated/relay-block-v0.3.0-alpha.1.bundle.schema.yaml",
    "schemas/v0.3.0-alpha.1/migration-evidence.schema.yaml",
    "schemas/v0.3.0-alpha.1/migration-audit.schema.yaml",
]


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def complete_protocol_index() -> str:
    lines = [
        "BEGIN_MADP_BUNDLE_METADATA",
        f"protocol_version: {VERSION}",
        "status: GENERATED_DISTRIBUTION_DRAFT_INDEX_ONLY",
        f"source_branch: {SOURCE_BRANCH}",
        "generator: scripts/generate_text_bundles.py",
        "limitations:",
        "- This committed alpha artifact is a reproducible source index, not the self-contained upload artifact.",
        "- The self-contained artifact is generated by CI as complete-protocol-bundle.full.txt.",
        "- It is not released or tagged.",
        "included_sources:",
    ]
    lines.extend(f"- {source}" for source in SELF_CONTAINED_SOURCES)
    lines.extend(
        [
            "END_MADP_BUNDLE_METADATA",
            "",
            "Generate committed indexes:",
            "python scripts/generate_text_bundles.py",
            "",
            "Generate a self-contained upload bundle:",
            "python scripts/generate_text_bundles.py --output-dir tmp/generated-v030",
            "",
            "Check committed indexes:",
            "python scripts/generate_text_bundles.py --check",
            "",
        ]
    )
    return "\n".join(lines)


def migration_fixture_index() -> str:
    lines = [
        f"{VERSION} migration fixture index",
        "status: GENERATED_DISTRIBUTION_DRAFT_INDEX_ONLY",
        "generator: scripts/generate_text_bundles.py",
        "",
    ]
    for directory in sorted(path for path in FIXTURES.iterdir() if path.is_dir()):
        manifest = yaml.safe_load((directory / "manifest.yaml").read_text(encoding="utf-8"))
        lines.append(f"{manifest['fixture_id']}: {manifest['purpose']}")
        lines.append(f"  semantic_status: {manifest.get('semantic_status', 'DEFERRED')}")
        lines.append(f"  required_files: {', '.join(manifest.get('required_files', []))}")
    lines.extend(
        [
            "",
            "Validation commands:",
            "python scripts/run_schema_fixture_checks.py all --json",
            "python scripts/check_migration_invariants_v030.py",
            "",
        ]
    )
    return "\n".join(lines)


def committed_outputs() -> dict[Path, str]:
    return {
        BOOTSTRAP / "complete-protocol-bundle.txt": complete_protocol_index(),
        BOOTSTRAP / "migration-fixtures-bundle.txt": migration_fixture_index(),
    }


def source_records() -> list[dict[str, Any]]:
    records = []
    for relative in SELF_CONTAINED_SOURCES:
        data = (ROOT / relative).read_bytes()
        records.append(
            {
                "path": relative,
                "byte_length": len(data),
                "sha256": sha256(data),
                "data": data,
            }
        )
    return records


def self_contained_bundle(records: list[dict[str, Any]], source_commit: str) -> str:
    payload_hash = hashlib.sha256()
    for record in records:
        payload_hash.update(record["path"].encode("utf-8"))
        payload_hash.update(b"\0")
        payload_hash.update(record["data"])
        payload_hash.update(b"\0")

    lines = [
        "BEGIN_MADP_BUNDLE_METADATA",
        f"protocol_version: {VERSION}",
        "status: GENERATED_SELF_CONTAINED_ALPHA_ARTIFACT",
        f"source_branch: {SOURCE_BRANCH}",
        f"source_commit: {source_commit}",
        "generator: scripts/generate_text_bundles.py",
        "source_encoding: BASE64_RFC4648",
        f"payload_sha256: {payload_hash.hexdigest()}",
        f"source_file_count: {len(records)}",
        "limitations:",
        "- This is an unreleased alpha artifact.",
        "- Formal universal interoperability is not claimed.",
        "sources:",
    ]
    for record in records:
        lines.append(f"- path: {record['path']}")
        lines.append(f"  byte_length: {record['byte_length']}")
        lines.append(f"  sha256: {record['sha256']}")
    lines.extend(["END_MADP_BUNDLE_METADATA", ""])

    for record in records:
        encoded = base64.b64encode(record["data"]).decode("ascii")
        lines.append(
            "BEGIN_MADP_SOURCE "
            f"path={record['path']} encoding=base64 "
            f"bytes={record['byte_length']} sha256={record['sha256']}"
        )
        lines.extend(textwrap.wrap(encoded, width=76))
        lines.append(f"END_MADP_SOURCE path={record['path']}")
        lines.append("")
    return "\n".join(lines)


def write_self_contained(output_dir: Path, source_commit: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    records = source_records()
    bundle = self_contained_bundle(records, source_commit)
    bundle_bytes = bundle.encode("utf-8")
    bundle_path = output_dir / "complete-protocol-bundle.full.txt"
    bundle_path.write_bytes(bundle_bytes)
    manifest = {
        "protocol_version": VERSION,
        "status": "GENERATED_SELF_CONTAINED_ALPHA_ARTIFACT",
        "source_branch": SOURCE_BRANCH,
        "source_commit": source_commit,
        "source_encoding": "BASE64_RFC4648",
        "bundle_file": bundle_path.name,
        "bundle_byte_length": len(bundle_bytes),
        "bundle_sha256": sha256(bundle_bytes),
        "sources": [
            {key: record[key] for key in ("path", "byte_length", "sha256")}
            for record in records
        ],
    }
    (output_dir / "complete-protocol-bundle.manifest.yaml").write_text(
        yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
        newline="",
    )
    print(f"WROTE: {bundle_path.relative_to(ROOT)}")
    print(f"WROTE: {(output_dir / 'complete-protocol-bundle.manifest.yaml').relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--source-commit", default=os.environ.get("GITHUB_SHA", "UNCOMMITTED"))
    args = parser.parse_args()
    failed = False
    for path, generated in committed_outputs().items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != generated:
                failed = True
                print(f"DRIFT: {path.relative_to(ROOT)}")
                for line in difflib.unified_diff(
                    current.splitlines(), generated.splitlines(),
                    fromfile="committed", tofile="generated", lineterm="",
                ):
                    print(line)
            else:
                print(f"OK: {path.relative_to(ROOT)}")
        elif args.output_dir is None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(generated, encoding="utf-8", newline="")
            print(f"WROTE: {path.relative_to(ROOT)}")

    if args.output_dir is not None:
        output_dir = args.output_dir if args.output_dir.is_absolute() else ROOT / args.output_dir
        write_self_contained(output_dir, args.source_commit)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
